// routes planes

GET http://localhost:8000/planes
Content-Type: application/json

### 

POST http://localhost:8000/planes 
Content-Type: application/json

{
    "constructeur": "avion 2021",
    "model" : "konexio"
} 

### 
PUT http://localhost:8000/planes/6188ebf53a12156e5b272bed
Content-Type: application/json

{
    "constructeur" : "AVION",
    "model": "KONEXIO 2021"
}
### 
DELETE http://localhost:8000/planes/61850de04f925f09c6bced22
Content-Type: application/json


// routes booking
###
GET http://localhost:8000/bookings
Content-Type: application/json



### 

POST http://localhost:8000/bookings 
Content-Type: application/json

{
    "from" : "Marseille",
    "to": "Lyon "
}

### 
PATCH http://localhost:8000/bookings/6188ede221a81ce09d4cc7e4
Content-Type: application/json

{
    "from" : "Cannes",
    "to": "Lyon "
}
### 
DELETE http://localhost:8000/bookings/61850de04f925f09c6bced22
Content-Type: application/json

